trigger:
  - main

pool:
  name: Default

steps:
  - task: NodeTool@0
    displayName: 'Instalar Node.js'
    inputs:
      versionSpec: '18.x'

  - script: |
      npm install
      npm run build || echo "No hay script build, continuando..."
    displayName: 'Instalar dependencias y construir app'

  - task: ArchiveFiles@2
    displayName: 'Empaquetar aplicación en ZIP'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
      replaceExistingArchive: true

  - task: AzureWebApp@1
    displayName: 'Desplegar en Azure Web App'
    inputs:
      azureSubscription: 'dd84aaae-d79f-4df5-b6d2-2b7120556d25'
      appType: 'webAppLinux'
      appName: 'PracticaPipeline'
      runtimeStack: 'NODE|18LTS'
      package: '$(Build.ArtifactStagingDirectory)/app.zip'
      startUpCommand: 'npm start'